# Generated by Django 5.2.4 on 2025-08-31 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('trip_type', models.CharField(choices=[('Solo', 'Solo'), ('Business', 'Business'), ('Family', 'Family'), ('Couple', 'Couple')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Future', 'Future'), ('Completed', 'Completed')], default='Future', max_length=20)),
                ('budget_range', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
