# Generated by Django 5.2.4 on 2025-08-31 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FavoriteMoment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_moments', to='trips.trip')),
            ],
        ),
    ]
